// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Race.proto

package com.randioo.box.protocol;

public final class Race {
  private Race() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class RaceJoinRaceRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use RaceJoinRaceRequest.newBuilder() to construct.
    private RaceJoinRaceRequest() {
      initFields();
    }
    private RaceJoinRaceRequest(boolean noInit) {}
    
    private static final RaceJoinRaceRequest defaultInstance;
    public static RaceJoinRaceRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public RaceJoinRaceRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.box.protocol.Race.internal_static_com_randioo_mahjong_public_server_protocol_RaceJoinRaceRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.box.protocol.Race.internal_static_com_randioo_mahjong_public_server_protocol_RaceJoinRaceRequest_fieldAccessorTable;
    }
    
    // optional int32 raceId = 1;
    public static final int RACEID_FIELD_NUMBER = 1;
    private boolean hasRaceId;
    private int raceId_ = 0;
    public boolean hasRaceId() { return hasRaceId; }
    public int getRaceId() { return raceId_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasRaceId()) {
        output.writeInt32(1, getRaceId());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasRaceId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getRaceId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.box.protocol.Race.RaceJoinRaceRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceJoinRaceRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceJoinRaceRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceJoinRaceRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceJoinRaceRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceJoinRaceRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceJoinRaceRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.box.protocol.Race.RaceJoinRaceRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.box.protocol.Race.RaceJoinRaceRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceJoinRaceRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.box.protocol.Race.RaceJoinRaceRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.box.protocol.Race.RaceJoinRaceRequest result;
      
      // Construct using com.randioo.mahjong_public_server.protocol.Race.RaceJoinRaceRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.box.protocol.Race.RaceJoinRaceRequest();
        return builder;
      }
      
      protected com.randioo.box.protocol.Race.RaceJoinRaceRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.box.protocol.Race.RaceJoinRaceRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.box.protocol.Race.RaceJoinRaceRequest.getDescriptor();
      }
      
      public com.randioo.box.protocol.Race.RaceJoinRaceRequest getDefaultInstanceForType() {
        return com.randioo.box.protocol.Race.RaceJoinRaceRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.box.protocol.Race.RaceJoinRaceRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.box.protocol.Race.RaceJoinRaceRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.box.protocol.Race.RaceJoinRaceRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.box.protocol.Race.RaceJoinRaceRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.box.protocol.Race.RaceJoinRaceRequest) {
          return mergeFrom((com.randioo.box.protocol.Race.RaceJoinRaceRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.box.protocol.Race.RaceJoinRaceRequest other) {
        if (other == com.randioo.box.protocol.Race.RaceJoinRaceRequest.getDefaultInstance()) return this;
        if (other.hasRaceId()) {
          setRaceId(other.getRaceId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setRaceId(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 raceId = 1;
      public boolean hasRaceId() {
        return result.hasRaceId();
      }
      public int getRaceId() {
        return result.getRaceId();
      }
      public Builder setRaceId(int value) {
        result.hasRaceId = true;
        result.raceId_ = value;
        return this;
      }
      public Builder clearRaceId() {
        result.hasRaceId = false;
        result.raceId_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.mahjong_public_server.protocol.RaceJoinRaceRequest)
    }
    
    static {
      defaultInstance = new RaceJoinRaceRequest(true);
      com.randioo.box.protocol.Race.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.mahjong_public_server.protocol.RaceJoinRaceRequest)
  }
  
  public static final class RaceJoinRaceResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use RaceJoinRaceResponse.newBuilder() to construct.
    private RaceJoinRaceResponse() {
      initFields();
    }
    private RaceJoinRaceResponse(boolean noInit) {}
    
    private static final RaceJoinRaceResponse defaultInstance;
    public static RaceJoinRaceResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public RaceJoinRaceResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.box.protocol.Race.internal_static_com_randioo_mahjong_public_server_protocol_RaceJoinRaceResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.box.protocol.Race.internal_static_com_randioo_mahjong_public_server_protocol_RaceJoinRaceResponse_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.box.protocol.Race.RaceJoinRaceResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceJoinRaceResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceJoinRaceResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceJoinRaceResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceJoinRaceResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceJoinRaceResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceJoinRaceResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.box.protocol.Race.RaceJoinRaceResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.box.protocol.Race.RaceJoinRaceResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceJoinRaceResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.box.protocol.Race.RaceJoinRaceResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.box.protocol.Race.RaceJoinRaceResponse result;
      
      // Construct using com.randioo.mahjong_public_server.protocol.Race.RaceJoinRaceResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.box.protocol.Race.RaceJoinRaceResponse();
        return builder;
      }
      
      protected com.randioo.box.protocol.Race.RaceJoinRaceResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.box.protocol.Race.RaceJoinRaceResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.box.protocol.Race.RaceJoinRaceResponse.getDescriptor();
      }
      
      public com.randioo.box.protocol.Race.RaceJoinRaceResponse getDefaultInstanceForType() {
        return com.randioo.box.protocol.Race.RaceJoinRaceResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.box.protocol.Race.RaceJoinRaceResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.box.protocol.Race.RaceJoinRaceResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.box.protocol.Race.RaceJoinRaceResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.box.protocol.Race.RaceJoinRaceResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.box.protocol.Race.RaceJoinRaceResponse) {
          return mergeFrom((com.randioo.box.protocol.Race.RaceJoinRaceResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.box.protocol.Race.RaceJoinRaceResponse other) {
        if (other == com.randioo.box.protocol.Race.RaceJoinRaceResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.mahjong_public_server.protocol.RaceJoinRaceResponse)
    }
    
    static {
      defaultInstance = new RaceJoinRaceResponse(true);
      com.randioo.box.protocol.Race.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.mahjong_public_server.protocol.RaceJoinRaceResponse)
  }
  
  public static final class SCRaceJoinRace extends
      com.google.protobuf.GeneratedMessage {
    // Use SCRaceJoinRace.newBuilder() to construct.
    private SCRaceJoinRace() {
      initFields();
    }
    private SCRaceJoinRace(boolean noInit) {}
    
    private static final SCRaceJoinRace defaultInstance;
    public static SCRaceJoinRace getDefaultInstance() {
      return defaultInstance;
    }
    
    public SCRaceJoinRace getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.box.protocol.Race.internal_static_com_randioo_mahjong_public_server_protocol_SCRaceJoinRace_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.box.protocol.Race.internal_static_com_randioo_mahjong_public_server_protocol_SCRaceJoinRace_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1 [default = 1];
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 1;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.box.protocol.Race.SCRaceJoinRace parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.box.protocol.Race.SCRaceJoinRace parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.box.protocol.Race.SCRaceJoinRace parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.box.protocol.Race.SCRaceJoinRace parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.box.protocol.Race.SCRaceJoinRace parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.box.protocol.Race.SCRaceJoinRace parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.box.protocol.Race.SCRaceJoinRace parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.box.protocol.Race.SCRaceJoinRace parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.box.protocol.Race.SCRaceJoinRace parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.box.protocol.Race.SCRaceJoinRace parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.box.protocol.Race.SCRaceJoinRace prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.box.protocol.Race.SCRaceJoinRace result;
      
      // Construct using com.randioo.mahjong_public_server.protocol.Race.SCRaceJoinRace.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.box.protocol.Race.SCRaceJoinRace();
        return builder;
      }
      
      protected com.randioo.box.protocol.Race.SCRaceJoinRace internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.box.protocol.Race.SCRaceJoinRace();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.box.protocol.Race.SCRaceJoinRace.getDescriptor();
      }
      
      public com.randioo.box.protocol.Race.SCRaceJoinRace getDefaultInstanceForType() {
        return com.randioo.box.protocol.Race.SCRaceJoinRace.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.box.protocol.Race.SCRaceJoinRace build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.box.protocol.Race.SCRaceJoinRace buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.box.protocol.Race.SCRaceJoinRace buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.box.protocol.Race.SCRaceJoinRace returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.box.protocol.Race.SCRaceJoinRace) {
          return mergeFrom((com.randioo.box.protocol.Race.SCRaceJoinRace)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.box.protocol.Race.SCRaceJoinRace other) {
        if (other == com.randioo.box.protocol.Race.SCRaceJoinRace.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1 [default = 1];
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 1;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.mahjong_public_server.protocol.SCRaceJoinRace)
    }
    
    static {
      defaultInstance = new SCRaceJoinRace(true);
      com.randioo.box.protocol.Race.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.mahjong_public_server.protocol.SCRaceJoinRace)
  }
  
  public static final class RaceShowQueueRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use RaceShowQueueRequest.newBuilder() to construct.
    private RaceShowQueueRequest() {
      initFields();
    }
    private RaceShowQueueRequest(boolean noInit) {}
    
    private static final RaceShowQueueRequest defaultInstance;
    public static RaceShowQueueRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public RaceShowQueueRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.box.protocol.Race.internal_static_com_randioo_mahjong_public_server_protocol_RaceShowQueueRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.box.protocol.Race.internal_static_com_randioo_mahjong_public_server_protocol_RaceShowQueueRequest_fieldAccessorTable;
    }
    
    // optional int32 raceId = 1;
    public static final int RACEID_FIELD_NUMBER = 1;
    private boolean hasRaceId;
    private int raceId_ = 0;
    public boolean hasRaceId() { return hasRaceId; }
    public int getRaceId() { return raceId_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasRaceId()) {
        output.writeInt32(1, getRaceId());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasRaceId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getRaceId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.box.protocol.Race.RaceShowQueueRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceShowQueueRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceShowQueueRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceShowQueueRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceShowQueueRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceShowQueueRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceShowQueueRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.box.protocol.Race.RaceShowQueueRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.box.protocol.Race.RaceShowQueueRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceShowQueueRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.box.protocol.Race.RaceShowQueueRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.box.protocol.Race.RaceShowQueueRequest result;
      
      // Construct using com.randioo.mahjong_public_server.protocol.Race.RaceShowQueueRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.box.protocol.Race.RaceShowQueueRequest();
        return builder;
      }
      
      protected com.randioo.box.protocol.Race.RaceShowQueueRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.box.protocol.Race.RaceShowQueueRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.box.protocol.Race.RaceShowQueueRequest.getDescriptor();
      }
      
      public com.randioo.box.protocol.Race.RaceShowQueueRequest getDefaultInstanceForType() {
        return com.randioo.box.protocol.Race.RaceShowQueueRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.box.protocol.Race.RaceShowQueueRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.box.protocol.Race.RaceShowQueueRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.box.protocol.Race.RaceShowQueueRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.box.protocol.Race.RaceShowQueueRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.box.protocol.Race.RaceShowQueueRequest) {
          return mergeFrom((com.randioo.box.protocol.Race.RaceShowQueueRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.box.protocol.Race.RaceShowQueueRequest other) {
        if (other == com.randioo.box.protocol.Race.RaceShowQueueRequest.getDefaultInstance()) return this;
        if (other.hasRaceId()) {
          setRaceId(other.getRaceId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setRaceId(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 raceId = 1;
      public boolean hasRaceId() {
        return result.hasRaceId();
      }
      public int getRaceId() {
        return result.getRaceId();
      }
      public Builder setRaceId(int value) {
        result.hasRaceId = true;
        result.raceId_ = value;
        return this;
      }
      public Builder clearRaceId() {
        result.hasRaceId = false;
        result.raceId_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.mahjong_public_server.protocol.RaceShowQueueRequest)
    }
    
    static {
      defaultInstance = new RaceShowQueueRequest(true);
      com.randioo.box.protocol.Race.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.mahjong_public_server.protocol.RaceShowQueueRequest)
  }
  
  public static final class RaceShowQueueResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use RaceShowQueueResponse.newBuilder() to construct.
    private RaceShowQueueResponse() {
      initFields();
    }
    private RaceShowQueueResponse(boolean noInit) {}
    
    private static final RaceShowQueueResponse defaultInstance;
    public static RaceShowQueueResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public RaceShowQueueResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.box.protocol.Race.internal_static_com_randioo_mahjong_public_server_protocol_RaceShowQueueResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.box.protocol.Race.internal_static_com_randioo_mahjong_public_server_protocol_RaceShowQueueResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1 [default = 1];
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 1;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    // repeated .com.randioo.mahjong_public_server.protocol.AudienceData audienceData = 2;
    public static final int AUDIENCEDATA_FIELD_NUMBER = 2;
    private java.util.List<com.randioo.box.protocol.Entity.AudienceData> audienceData_ =
      java.util.Collections.emptyList();
    public java.util.List<com.randioo.box.protocol.Entity.AudienceData> getAudienceDataList() {
      return audienceData_;
    }
    public int getAudienceDataCount() { return audienceData_.size(); }
    public com.randioo.box.protocol.Entity.AudienceData getAudienceData(int index) {
      return audienceData_.get(index);
    }
    
    // repeated .com.randioo.mahjong_public_server.protocol.GameRoleData gameRoleData = 3;
    public static final int GAMEROLEDATA_FIELD_NUMBER = 3;
    private java.util.List<com.randioo.box.protocol.Entity.GameRoleData> gameRoleData_ =
      java.util.Collections.emptyList();
    public java.util.List<com.randioo.box.protocol.Entity.GameRoleData> getGameRoleDataList() {
      return gameRoleData_;
    }
    public int getGameRoleDataCount() { return gameRoleData_.size(); }
    public com.randioo.box.protocol.Entity.GameRoleData getGameRoleData(int index) {
      return gameRoleData_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      for (com.randioo.box.protocol.Entity.AudienceData element : getAudienceDataList()) {
        output.writeMessage(2, element);
      }
      for (com.randioo.box.protocol.Entity.GameRoleData element : getGameRoleDataList()) {
        output.writeMessage(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      for (com.randioo.box.protocol.Entity.AudienceData element : getAudienceDataList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      for (com.randioo.box.protocol.Entity.GameRoleData element : getGameRoleDataList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.box.protocol.Race.RaceShowQueueResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceShowQueueResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceShowQueueResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceShowQueueResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceShowQueueResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceShowQueueResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceShowQueueResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.box.protocol.Race.RaceShowQueueResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.box.protocol.Race.RaceShowQueueResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.box.protocol.Race.RaceShowQueueResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.box.protocol.Race.RaceShowQueueResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.box.protocol.Race.RaceShowQueueResponse result;
      
      // Construct using com.randioo.mahjong_public_server.protocol.Race.RaceShowQueueResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.box.protocol.Race.RaceShowQueueResponse();
        return builder;
      }
      
      protected com.randioo.box.protocol.Race.RaceShowQueueResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.box.protocol.Race.RaceShowQueueResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.box.protocol.Race.RaceShowQueueResponse.getDescriptor();
      }
      
      public com.randioo.box.protocol.Race.RaceShowQueueResponse getDefaultInstanceForType() {
        return com.randioo.box.protocol.Race.RaceShowQueueResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.box.protocol.Race.RaceShowQueueResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.box.protocol.Race.RaceShowQueueResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.box.protocol.Race.RaceShowQueueResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.audienceData_ != java.util.Collections.EMPTY_LIST) {
          result.audienceData_ =
            java.util.Collections.unmodifiableList(result.audienceData_);
        }
        if (result.gameRoleData_ != java.util.Collections.EMPTY_LIST) {
          result.gameRoleData_ =
            java.util.Collections.unmodifiableList(result.gameRoleData_);
        }
        com.randioo.box.protocol.Race.RaceShowQueueResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.box.protocol.Race.RaceShowQueueResponse) {
          return mergeFrom((com.randioo.box.protocol.Race.RaceShowQueueResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.box.protocol.Race.RaceShowQueueResponse other) {
        if (other == com.randioo.box.protocol.Race.RaceShowQueueResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (!other.audienceData_.isEmpty()) {
          if (result.audienceData_.isEmpty()) {
            result.audienceData_ = new java.util.ArrayList<com.randioo.box.protocol.Entity.AudienceData>();
          }
          result.audienceData_.addAll(other.audienceData_);
        }
        if (!other.gameRoleData_.isEmpty()) {
          if (result.gameRoleData_.isEmpty()) {
            result.gameRoleData_ = new java.util.ArrayList<com.randioo.box.protocol.Entity.GameRoleData>();
          }
          result.gameRoleData_.addAll(other.gameRoleData_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
            case 18: {
              com.randioo.box.protocol.Entity.AudienceData.Builder subBuilder = com.randioo.box.protocol.Entity.AudienceData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAudienceData(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.randioo.box.protocol.Entity.GameRoleData.Builder subBuilder = com.randioo.box.protocol.Entity.GameRoleData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addGameRoleData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1 [default = 1];
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 1;
        return this;
      }
      
      // repeated .com.randioo.mahjong_public_server.protocol.AudienceData audienceData = 2;
      public java.util.List<com.randioo.box.protocol.Entity.AudienceData> getAudienceDataList() {
        return java.util.Collections.unmodifiableList(result.audienceData_);
      }
      public int getAudienceDataCount() {
        return result.getAudienceDataCount();
      }
      public com.randioo.box.protocol.Entity.AudienceData getAudienceData(int index) {
        return result.getAudienceData(index);
      }
      public Builder setAudienceData(int index, com.randioo.box.protocol.Entity.AudienceData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.audienceData_.set(index, value);
        return this;
      }
      public Builder setAudienceData(int index, com.randioo.box.protocol.Entity.AudienceData.Builder builderForValue) {
        result.audienceData_.set(index, builderForValue.build());
        return this;
      }
      public Builder addAudienceData(com.randioo.box.protocol.Entity.AudienceData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.audienceData_.isEmpty()) {
          result.audienceData_ = new java.util.ArrayList<com.randioo.box.protocol.Entity.AudienceData>();
        }
        result.audienceData_.add(value);
        return this;
      }
      public Builder addAudienceData(com.randioo.box.protocol.Entity.AudienceData.Builder builderForValue) {
        if (result.audienceData_.isEmpty()) {
          result.audienceData_ = new java.util.ArrayList<com.randioo.box.protocol.Entity.AudienceData>();
        }
        result.audienceData_.add(builderForValue.build());
        return this;
      }
      public Builder addAllAudienceData(
          java.lang.Iterable<? extends com.randioo.box.protocol.Entity.AudienceData> values) {
        if (result.audienceData_.isEmpty()) {
          result.audienceData_ = new java.util.ArrayList<com.randioo.box.protocol.Entity.AudienceData>();
        }
        super.addAll(values, result.audienceData_);
        return this;
      }
      public Builder clearAudienceData() {
        result.audienceData_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .com.randioo.mahjong_public_server.protocol.GameRoleData gameRoleData = 3;
      public java.util.List<com.randioo.box.protocol.Entity.GameRoleData> getGameRoleDataList() {
        return java.util.Collections.unmodifiableList(result.gameRoleData_);
      }
      public int getGameRoleDataCount() {
        return result.getGameRoleDataCount();
      }
      public com.randioo.box.protocol.Entity.GameRoleData getGameRoleData(int index) {
        return result.getGameRoleData(index);
      }
      public Builder setGameRoleData(int index, com.randioo.box.protocol.Entity.GameRoleData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.gameRoleData_.set(index, value);
        return this;
      }
      public Builder setGameRoleData(int index, com.randioo.box.protocol.Entity.GameRoleData.Builder builderForValue) {
        result.gameRoleData_.set(index, builderForValue.build());
        return this;
      }
      public Builder addGameRoleData(com.randioo.box.protocol.Entity.GameRoleData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.gameRoleData_.isEmpty()) {
          result.gameRoleData_ = new java.util.ArrayList<com.randioo.box.protocol.Entity.GameRoleData>();
        }
        result.gameRoleData_.add(value);
        return this;
      }
      public Builder addGameRoleData(com.randioo.box.protocol.Entity.GameRoleData.Builder builderForValue) {
        if (result.gameRoleData_.isEmpty()) {
          result.gameRoleData_ = new java.util.ArrayList<com.randioo.box.protocol.Entity.GameRoleData>();
        }
        result.gameRoleData_.add(builderForValue.build());
        return this;
      }
      public Builder addAllGameRoleData(
          java.lang.Iterable<? extends com.randioo.box.protocol.Entity.GameRoleData> values) {
        if (result.gameRoleData_.isEmpty()) {
          result.gameRoleData_ = new java.util.ArrayList<com.randioo.box.protocol.Entity.GameRoleData>();
        }
        super.addAll(values, result.gameRoleData_);
        return this;
      }
      public Builder clearGameRoleData() {
        result.gameRoleData_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.mahjong_public_server.protocol.RaceShowQueueResponse)
    }
    
    static {
      defaultInstance = new RaceShowQueueResponse(true);
      com.randioo.box.protocol.Race.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.mahjong_public_server.protocol.RaceShowQueueResponse)
  }
  
  public static final class SCRaceQueueChange extends
      com.google.protobuf.GeneratedMessage {
    // Use SCRaceQueueChange.newBuilder() to construct.
    private SCRaceQueueChange() {
      initFields();
    }
    private SCRaceQueueChange(boolean noInit) {}
    
    private static final SCRaceQueueChange defaultInstance;
    public static SCRaceQueueChange getDefaultInstance() {
      return defaultInstance;
    }
    
    public SCRaceQueueChange getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.box.protocol.Race.internal_static_com_randioo_mahjong_public_server_protocol_SCRaceQueueChange_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.box.protocol.Race.internal_static_com_randioo_mahjong_public_server_protocol_SCRaceQueueChange_fieldAccessorTable;
    }
    
    // repeated .com.randioo.mahjong_public_server.protocol.AudienceData audienceData = 2;
    public static final int AUDIENCEDATA_FIELD_NUMBER = 2;
    private java.util.List<com.randioo.box.protocol.Entity.AudienceData> audienceData_ =
      java.util.Collections.emptyList();
    public java.util.List<com.randioo.box.protocol.Entity.AudienceData> getAudienceDataList() {
      return audienceData_;
    }
    public int getAudienceDataCount() { return audienceData_.size(); }
    public com.randioo.box.protocol.Entity.AudienceData getAudienceData(int index) {
      return audienceData_.get(index);
    }
    
    // repeated .com.randioo.mahjong_public_server.protocol.GameRoleData gameRoleData = 3;
    public static final int GAMEROLEDATA_FIELD_NUMBER = 3;
    private java.util.List<com.randioo.box.protocol.Entity.GameRoleData> gameRoleData_ =
      java.util.Collections.emptyList();
    public java.util.List<com.randioo.box.protocol.Entity.GameRoleData> getGameRoleDataList() {
      return gameRoleData_;
    }
    public int getGameRoleDataCount() { return gameRoleData_.size(); }
    public com.randioo.box.protocol.Entity.GameRoleData getGameRoleData(int index) {
      return gameRoleData_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.randioo.box.protocol.Entity.AudienceData element : getAudienceDataList()) {
        output.writeMessage(2, element);
      }
      for (com.randioo.box.protocol.Entity.GameRoleData element : getGameRoleDataList()) {
        output.writeMessage(3, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (com.randioo.box.protocol.Entity.AudienceData element : getAudienceDataList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      for (com.randioo.box.protocol.Entity.GameRoleData element : getGameRoleDataList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.box.protocol.Race.SCRaceQueueChange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.box.protocol.Race.SCRaceQueueChange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.box.protocol.Race.SCRaceQueueChange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.box.protocol.Race.SCRaceQueueChange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.box.protocol.Race.SCRaceQueueChange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.box.protocol.Race.SCRaceQueueChange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.box.protocol.Race.SCRaceQueueChange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.box.protocol.Race.SCRaceQueueChange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.box.protocol.Race.SCRaceQueueChange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.box.protocol.Race.SCRaceQueueChange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.box.protocol.Race.SCRaceQueueChange prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.box.protocol.Race.SCRaceQueueChange result;
      
      // Construct using com.randioo.mahjong_public_server.protocol.Race.SCRaceQueueChange.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.box.protocol.Race.SCRaceQueueChange();
        return builder;
      }
      
      protected com.randioo.box.protocol.Race.SCRaceQueueChange internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.box.protocol.Race.SCRaceQueueChange();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.box.protocol.Race.SCRaceQueueChange.getDescriptor();
      }
      
      public com.randioo.box.protocol.Race.SCRaceQueueChange getDefaultInstanceForType() {
        return com.randioo.box.protocol.Race.SCRaceQueueChange.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.box.protocol.Race.SCRaceQueueChange build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.box.protocol.Race.SCRaceQueueChange buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.box.protocol.Race.SCRaceQueueChange buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.audienceData_ != java.util.Collections.EMPTY_LIST) {
          result.audienceData_ =
            java.util.Collections.unmodifiableList(result.audienceData_);
        }
        if (result.gameRoleData_ != java.util.Collections.EMPTY_LIST) {
          result.gameRoleData_ =
            java.util.Collections.unmodifiableList(result.gameRoleData_);
        }
        com.randioo.box.protocol.Race.SCRaceQueueChange returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.box.protocol.Race.SCRaceQueueChange) {
          return mergeFrom((com.randioo.box.protocol.Race.SCRaceQueueChange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.box.protocol.Race.SCRaceQueueChange other) {
        if (other == com.randioo.box.protocol.Race.SCRaceQueueChange.getDefaultInstance()) return this;
        if (!other.audienceData_.isEmpty()) {
          if (result.audienceData_.isEmpty()) {
            result.audienceData_ = new java.util.ArrayList<com.randioo.box.protocol.Entity.AudienceData>();
          }
          result.audienceData_.addAll(other.audienceData_);
        }
        if (!other.gameRoleData_.isEmpty()) {
          if (result.gameRoleData_.isEmpty()) {
            result.gameRoleData_ = new java.util.ArrayList<com.randioo.box.protocol.Entity.GameRoleData>();
          }
          result.gameRoleData_.addAll(other.gameRoleData_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 18: {
              com.randioo.box.protocol.Entity.AudienceData.Builder subBuilder = com.randioo.box.protocol.Entity.AudienceData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAudienceData(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.randioo.box.protocol.Entity.GameRoleData.Builder subBuilder = com.randioo.box.protocol.Entity.GameRoleData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addGameRoleData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .com.randioo.mahjong_public_server.protocol.AudienceData audienceData = 2;
      public java.util.List<com.randioo.box.protocol.Entity.AudienceData> getAudienceDataList() {
        return java.util.Collections.unmodifiableList(result.audienceData_);
      }
      public int getAudienceDataCount() {
        return result.getAudienceDataCount();
      }
      public com.randioo.box.protocol.Entity.AudienceData getAudienceData(int index) {
        return result.getAudienceData(index);
      }
      public Builder setAudienceData(int index, com.randioo.box.protocol.Entity.AudienceData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.audienceData_.set(index, value);
        return this;
      }
      public Builder setAudienceData(int index, com.randioo.box.protocol.Entity.AudienceData.Builder builderForValue) {
        result.audienceData_.set(index, builderForValue.build());
        return this;
      }
      public Builder addAudienceData(com.randioo.box.protocol.Entity.AudienceData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.audienceData_.isEmpty()) {
          result.audienceData_ = new java.util.ArrayList<com.randioo.box.protocol.Entity.AudienceData>();
        }
        result.audienceData_.add(value);
        return this;
      }
      public Builder addAudienceData(com.randioo.box.protocol.Entity.AudienceData.Builder builderForValue) {
        if (result.audienceData_.isEmpty()) {
          result.audienceData_ = new java.util.ArrayList<com.randioo.box.protocol.Entity.AudienceData>();
        }
        result.audienceData_.add(builderForValue.build());
        return this;
      }
      public Builder addAllAudienceData(
          java.lang.Iterable<? extends com.randioo.box.protocol.Entity.AudienceData> values) {
        if (result.audienceData_.isEmpty()) {
          result.audienceData_ = new java.util.ArrayList<com.randioo.box.protocol.Entity.AudienceData>();
        }
        super.addAll(values, result.audienceData_);
        return this;
      }
      public Builder clearAudienceData() {
        result.audienceData_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .com.randioo.mahjong_public_server.protocol.GameRoleData gameRoleData = 3;
      public java.util.List<com.randioo.box.protocol.Entity.GameRoleData> getGameRoleDataList() {
        return java.util.Collections.unmodifiableList(result.gameRoleData_);
      }
      public int getGameRoleDataCount() {
        return result.getGameRoleDataCount();
      }
      public com.randioo.box.protocol.Entity.GameRoleData getGameRoleData(int index) {
        return result.getGameRoleData(index);
      }
      public Builder setGameRoleData(int index, com.randioo.box.protocol.Entity.GameRoleData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.gameRoleData_.set(index, value);
        return this;
      }
      public Builder setGameRoleData(int index, com.randioo.box.protocol.Entity.GameRoleData.Builder builderForValue) {
        result.gameRoleData_.set(index, builderForValue.build());
        return this;
      }
      public Builder addGameRoleData(com.randioo.box.protocol.Entity.GameRoleData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.gameRoleData_.isEmpty()) {
          result.gameRoleData_ = new java.util.ArrayList<com.randioo.box.protocol.Entity.GameRoleData>();
        }
        result.gameRoleData_.add(value);
        return this;
      }
      public Builder addGameRoleData(com.randioo.box.protocol.Entity.GameRoleData.Builder builderForValue) {
        if (result.gameRoleData_.isEmpty()) {
          result.gameRoleData_ = new java.util.ArrayList<com.randioo.box.protocol.Entity.GameRoleData>();
        }
        result.gameRoleData_.add(builderForValue.build());
        return this;
      }
      public Builder addAllGameRoleData(
          java.lang.Iterable<? extends com.randioo.box.protocol.Entity.GameRoleData> values) {
        if (result.gameRoleData_.isEmpty()) {
          result.gameRoleData_ = new java.util.ArrayList<com.randioo.box.protocol.Entity.GameRoleData>();
        }
        super.addAll(values, result.gameRoleData_);
        return this;
      }
      public Builder clearGameRoleData() {
        result.gameRoleData_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.mahjong_public_server.protocol.SCRaceQueueChange)
    }
    
    static {
      defaultInstance = new SCRaceQueueChange(true);
      com.randioo.box.protocol.Race.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.mahjong_public_server.protocol.SCRaceQueueChange)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_mahjong_public_server_protocol_RaceJoinRaceRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_mahjong_public_server_protocol_RaceJoinRaceRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_mahjong_public_server_protocol_RaceJoinRaceResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_mahjong_public_server_protocol_RaceJoinRaceResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_mahjong_public_server_protocol_SCRaceJoinRace_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_mahjong_public_server_protocol_SCRaceJoinRace_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_mahjong_public_server_protocol_RaceShowQueueRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_mahjong_public_server_protocol_RaceShowQueueRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_mahjong_public_server_protocol_RaceShowQueueResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_mahjong_public_server_protocol_RaceShowQueueResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_mahjong_public_server_protocol_SCRaceQueueChange_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_mahjong_public_server_protocol_SCRaceQueueChange_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nRace.proto\022*com.randioo.mahjong_public" +
      "_server.protocol\032\014Entity.proto\"%\n\023RaceJo" +
      "inRaceRequest\022\016\n\006raceId\030\001 \001(\005\"\026\n\024RaceJoi" +
      "nRaceResponse\"&\n\016SCRaceJoinRace\022\024\n\terror" +
      "Code\030\001 \001(\005:\0011\"&\n\024RaceShowQueueRequest\022\016\n" +
      "\006raceId\030\001 \001(\005\"\315\001\n\025RaceShowQueueResponse\022" +
      "\024\n\terrorCode\030\001 \001(\005:\0011\022N\n\014audienceData\030\002 " +
      "\003(\01328.com.randioo.mahjong_public_server." +
      "protocol.AudienceData\022N\n\014gameRoleData\030\003 " +
      "\003(\01328.com.randioo.mahjong_public_server.",
      "protocol.GameRoleData\"\263\001\n\021SCRaceQueueCha" +
      "nge\022N\n\014audienceData\030\002 \003(\01328.com.randioo." +
      "mahjong_public_server.protocol.AudienceD" +
      "ata\022N\n\014gameRoleData\030\003 \003(\01328.com.randioo." +
      "mahjong_public_server.protocol.GameRoleD" +
      "ata"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_mahjong_public_server_protocol_RaceJoinRaceRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_mahjong_public_server_protocol_RaceJoinRaceRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_mahjong_public_server_protocol_RaceJoinRaceRequest_descriptor,
              new java.lang.String[] { "RaceId", },
              com.randioo.box.protocol.Race.RaceJoinRaceRequest.class,
              com.randioo.box.protocol.Race.RaceJoinRaceRequest.Builder.class);
          internal_static_com_randioo_mahjong_public_server_protocol_RaceJoinRaceResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_mahjong_public_server_protocol_RaceJoinRaceResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_mahjong_public_server_protocol_RaceJoinRaceResponse_descriptor,
              new java.lang.String[] { },
              com.randioo.box.protocol.Race.RaceJoinRaceResponse.class,
              com.randioo.box.protocol.Race.RaceJoinRaceResponse.Builder.class);
          internal_static_com_randioo_mahjong_public_server_protocol_SCRaceJoinRace_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_randioo_mahjong_public_server_protocol_SCRaceJoinRace_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_mahjong_public_server_protocol_SCRaceJoinRace_descriptor,
              new java.lang.String[] { "ErrorCode", },
              com.randioo.box.protocol.Race.SCRaceJoinRace.class,
              com.randioo.box.protocol.Race.SCRaceJoinRace.Builder.class);
          internal_static_com_randioo_mahjong_public_server_protocol_RaceShowQueueRequest_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_randioo_mahjong_public_server_protocol_RaceShowQueueRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_mahjong_public_server_protocol_RaceShowQueueRequest_descriptor,
              new java.lang.String[] { "RaceId", },
              com.randioo.box.protocol.Race.RaceShowQueueRequest.class,
              com.randioo.box.protocol.Race.RaceShowQueueRequest.Builder.class);
          internal_static_com_randioo_mahjong_public_server_protocol_RaceShowQueueResponse_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_com_randioo_mahjong_public_server_protocol_RaceShowQueueResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_mahjong_public_server_protocol_RaceShowQueueResponse_descriptor,
              new java.lang.String[] { "ErrorCode", "AudienceData", "GameRoleData", },
              com.randioo.box.protocol.Race.RaceShowQueueResponse.class,
              com.randioo.box.protocol.Race.RaceShowQueueResponse.Builder.class);
          internal_static_com_randioo_mahjong_public_server_protocol_SCRaceQueueChange_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_com_randioo_mahjong_public_server_protocol_SCRaceQueueChange_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_mahjong_public_server_protocol_SCRaceQueueChange_descriptor,
              new java.lang.String[] { "AudienceData", "GameRoleData", },
              com.randioo.box.protocol.Race.SCRaceQueueChange.class,
              com.randioo.box.protocol.Race.SCRaceQueueChange.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.box.protocol.Entity.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
